spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

---
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fileUpload
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate